site_name: Swadhin Resume
site_url: https://swadhinsekhar.github.io
theme:
  name: material
  features:
    - navigation.tabs
    - header.autohide
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: purple 
extra_css: [css/style.css]

plugins:
  - search
extra:
  generator: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/swadhinsekhar"  target="_blank" rel="noopener">Swadhin Sekhar</a>

nav:
  - Resume: index.md
  - Technical Contents:
      - Overview: technical-contents/overview.md
      - IPSec Demonstration : technical-contents/ipsec-demo.md
